# -*- coding: utf-8 -*-
"""ASSIGNMENT_3_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAn079BaQzdGdmpza83Y_PHEYibuuwwF

Q1) Generate all prime numbers less than 100.Print them in a spiral format (like a clockwise
square spiral) of minimal size that fits all primes.
"""

import math

prime =[]
for i in range (1,101,1):
  c=0
  for j in range(2,int(i/2)):
    if i % j == 0:
      c+=1
  if c == 0:
    prime.append(i)
n= len(prime)
prime.append(-1)
e = math.ceil(n/4) +1
z = n
#print(e)
for i in range(e):
  print(prime[i],end="  ")
print()
for i in range(8,6+e):
  for j in range(e-1):
    if j==e-2:
      print(prime[i])
    elif 1 <=j <e-2:
      print(end="   ")
    elif z ==27:
      print("  ",end="    ")
    else:
      print(prime[z],end="    ")
  z-=1
for i in range(13+e,13,-1):
  print(prime[i],end=" ")

"""Q2) You are a data analyst at a streaming platform, managing user interactions, analytics,
and daily operations. Use a for loop to create a text-based graph of hourly views. For
example, use * to represent every 5 views.
"""

n = int(input("Enter the number of hours--> "))
views =[]
star=[]
for i in range(n):
  c=int(input("Hour {} ->".format(i+1)))
  views.append(c)
  star.append(int(c/5))
print(views)
print(star)
ch = "*"
for i in range(n):
  print("Hour {}--> {}".format(i,ch*star[i]))

"""
Q3) Each video watched generates revenue based on ad impressions:
 First 10 views: $0.50 per view
 Next 20 views: $0.30 per view
 Remaining views: $0.10 per view
You are given hourly views for the day. Calculate total daily revenue."""

views=[]
for i in range(24):
  c=int(input("Hour {} ->".format(i+1)))
  views.append(c)
t= sum(views)
if t < 10 :
  r = t * 0.50
elif t < 30:
  r = 10 *0.5 + (t-10)*0.30
else:
  r = 10 *0.5 + 20*0.30 + (t-30)*0.10
print("Total daily revenue--> $0",r)

